#!/usr/bin/env python3
"""build.py — Validate evidence and compile the technical report."""
import os, sys, subprocess, shutil

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(REPO, 'report')
PDF_SRC = os.path.join(REPORT, 'main.pdf')
PDF_DST = os.path.join(REPO, 'technical-report.pdf')

def validate():
    r = subprocess.run([sys.executable, os.path.join(REPO, 'scripts', 'validate_evidence.py')],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print('❌ Evidence validation failed:\n' + r.stderr)
        sys.exit(1)
    print('✅ Evidence validated')

def generate(e):
    """Section .tex files are pre-generated by scripts/generate_sections.py.
    This function only updates the metric count marker."""
    metrics = e.get('metrics', {})
    # Update sections/04 to use dynamic metric count
    path = os.path.join(REPO, 'report', 'sections', '04_data_and_methodology.tex')
    if os.path.exists(path):
        with open(path) as f:
            content = f.read()
        import re
        content = re.sub(r'\d+ metrics', f'{len(metrics)} metrics', content)
        with open(path, 'w') as f:
            f.write(content)
    print(f'✅ {len(metrics)} metrics confirmed')

def compile_latex():
    if not shutil.which('pdflatex'):
        print('⚠️  pdflatex not found.')
        return False
    for i in range(2):
        r = subprocess.run(['pdflatex', '-interaction=nonstopmode', 'main.tex'],
                          cwd=REPORT, capture_output=True, text=True)
        errs = [l for l in r.stdout.split('\n') if l.startswith('!')]
        if i == 1 and errs:
            print(f'❌ {len(errs)} LaTeX errors')
            for l in errs[:3]: print(f'   {l}')
            return False
    if os.path.exists(PDF_SRC):
        shutil.copy(PDF_SRC, PDF_DST)
        print(f'✅ PDF: {PDF_DST}')
        return True
    print('❌ PDF not generated')
    return False

def main():
    import json
    with open(os.path.join(REPO, 'data', 'evidence.json')) as f:
        e = json.load(f)
    validate()
    generate(e)
    if not compile_latex():
        sys.exit(1)
    print('✅ Build complete')

if __name__ == '__main__':
    main()
