#!/usr/bin/env python3
"""build.py — Generate evidence-backed LaTeX fragments and compile the technical report."""
import json, os, sys, subprocess, shutil

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EVIDENCE = os.path.join(REPO_ROOT, 'data', 'evidence.json')
REPORT_DIR = os.path.join(REPO_ROOT, 'report')
GEN_DIR = os.path.join(REPORT_DIR, 'generated')
MAIN = os.path.join(REPORT_DIR, 'main.tex')
OUTPUT = os.path.join(REPO_ROOT, 'technical-report.pdf')

def esc(s):
    """Escape LaTeX special characters."""
    return str(s).replace('\\', '\\textbackslash{}').replace('&', '\\&').replace('%', '\\%').replace('$', '\\$').replace('#', '\\#').replace('_', '\\_').replace('{', '\\{').replace('}', '\\}').replace('~', '\\textasciitilde{}').replace('^', '\\textasciicircum{}')

def load_evidence():
    with open(EVIDENCE) as f:
        return json.load(f)

def validate():
    """Run the existing validator."""
    result = subprocess.run([sys.executable, os.path.join(REPO_ROOT, 'scripts', 'validate_evidence.py')],
                          capture_output=True, text=True)
    if result.returncode != 0:
        print("❌ Evidence validation failed:")
        print(result.stderr)
        sys.exit(1)
    print("✅ Evidence validation passed")

def generate_macros(e):
    """Generate evidence_macros.tex from evidence.json."""
    m = e['metrics']
    macros = [
        '% Auto-generated from data/evidence.json — DO NOT EDIT',
        f'% Generated by build.py',
        '',
        '% ---- Three Collapses Metrics ----',
        f'\\newcommand{{\\InitialIC}}{{{m["target_leak_before_ic"]["value"]}}}',
        f'\\newcommand{{\\CorrectedIC}}{{{m["target_leak_after_ic"]["value"]}}}',
    ]
    # Compute 89%
    before = m['target_leak_before_ic']['value']
    after = m['target_leak_after_ic']['value']
    pct = (before - after) / abs(before) * 100
    macros.append(f'\\newcommand{{\\RelativeCollapse}}{{{pct:.0f}\\%}}')
    macros.append(f'\\newcommand{{\\AbsoluteDecline}}{{{before - after:.2f}}}')
    
    macros.extend([
        '',
        '% ---- Baseline Metrics ----',
        f'\\newcommand{{\\BaselineIC}}{{{m["frozen_baseline_mean_ic"]["value"]:.3f}}}',
        f'\\newcommand{{\\NWtStat}}{{{m["frozen_baseline_nw_t6"]["value"]:.1f}}}',
        f'\\newcommand{{\\BootstrapCI}}{{{m["frozen_baseline_bootstrap_ci_lower"]["value"]:.3f}}}',
        '',
        '% ---- Portfolio Results ----',
        f'\\newcommand{{\\U100NetAnnual}}{{{m["u100_raw_net_annual"]["value"]*100:.1f}\\%}}',
        f'\\newcommand{{\\U50NetAnnual}}{{{abs(m["u50_resid_net_annual"]["value"])*100:.1f}\\%}}',
        f'\\newcommand{{\\U50MaxDD}}{{{m["u50_max_drawdown"]["value"]*100:.1f}\\%}}',
        '',
        '% ---- Quintile Attribution ----',
        f'\\newcommand{{\\Q1Excess}}{{{m["q1_within_excess"]["value"]*100:.1f}\\%}}',
        f'\\newcommand{{\\Q1HoldingsShare}}{{{m["q1_share_of_u100_holdings"]["value"]*100:.1f}\\%}}',
        '',
        '% ---- Null Infrastructure ----',
        f'\\newcommand{{\\NullIC}}{{{m["iid_null_mean_ic"]["value"]:.3f}}}',
        f'\\newcommand{{\\PermAuditCorr}}{{{m["permutation_audit_corr"]["value"]:.3f}}}',
        '',
        '% ---- Multi-Horizon ----',
        f'\\newcommand{{\\H3NetAnnual}}{{{abs(m["h3_u50_net_annual"]["value"])*100:.1f}\\%}}',
        f'\\newcommand{{\\H6NetAnnual}}{{{abs(m["h6_u50_net_annual"]["value"])*100:.1f}\\%}}',
        '',
        '% ---- Folds ----',
    ])
    folds = e.get('folds', {})
    for k in ['fold1', 'fold2', 'fold3']:
        if k in folds:
            f = folds[k]
            macros.append(f'\\newcommand{{\\{k.capitalize()}IC}}{{{f["ic"]:.3f}}}')
            macros.append(f'\\newcommand{{\\{k.capitalize()}ICIR}}{{{f["icir"]:.2f}}}')
            macros.append(f'\\newcommand{{\\{k.capitalize()}Pos}}{{{f["pos_rate"]*100:.0f}\\%}}')
    
    if 'pooled' in folds:
        p = folds['pooled']
        macros.append(f'\\newcommand{{\\PooledMonths}}{{{p["months"]}}}')
        macros.append(f'\\newcommand{{\\PooledIC}}{{{p["mean_ic"]:.3f}}}')
    
    with open(os.path.join(GEN_DIR, 'evidence_macros.tex'), 'w') as f:
        f.write('\n'.join(macros))
    print(f"✅ Generated {len(macros)} evidence macros")

def generate_tables(e):
    """Generate LaTeX table fragments from evidence."""
    m = e['metrics']
    
    # Experiment summary table
    rows = [r'  \toprule',
            r'  \textbf{Experiment} & \textbf{Key Metric} & \textbf{Value} & \textbf{Status} \\',
            r'  \midrule']
    
    experiments = [
        ('Target Timing', 'IC (before→after)', f'{m["target_leak_before_ic"]["value"]}→{m["target_leak_after_ic"]["value"]}', 'Invalid→Validated'),
        ('Cross-Fit Contamination', 'IC (before→after)', f'{m["crossfit_ic_before"]["value"]}→{m["crossfit_ic_after"]["value"]}', 'Invalid→Validated'),
        ('Frozen Baseline', 'Mean OOS IC', f'{m["frozen_baseline_mean_ic"]["value"]:.3f}', 'Validated'),
        ('U100 Portfolio', 'Net Annual Return', f'{m["u100_raw_net_annual"]["value"]*100:+.1f}\\%', 'Positive (Q1-driven)'),
        ('U50 Portfolio (RESID)', 'Net Annual Return', f'{m["u50_resid_net_annual"]["value"]*100:+.1f}\\%', 'Failed'),
        ('Q1 Within-Quintile', 'Monthly Excess', f'{m["q1_within_excess"]["value"]*100:+.1f}\\%', 'Validated'),
        ('H3 Multi-Horizon', 'U50 Net Annual', f'{m["h3_u50_net_annual"]["value"]*100:+.1f}\\%', 'Rejected'),
        ('H6 Multi-Horizon', 'U50 Net Annual', f'{m["h6_u50_net_annual"]["value"]*100:+.1f}\\%', 'Rejected'),
    ]
    for exp, metric, value, status in experiments:
        rows.append(f'  {esc(exp)} & {esc(metric)} & {esc(value)} & {esc(status)} \\\\')
    
    rows.extend([r'  \bottomrule'])
    
    with open(os.path.join(GEN_DIR, 'experiment_summary.tex'), 'w') as f:
        f.write('\n'.join(rows))
    
    # Portfolio results table
    rows2 = [r'  \toprule',
             r'  \textbf{Portfolio} & \textbf{Net Annual} & \textbf{Sharpe} & \textbf{Max DD} & \textbf{Excess} \\',
             r'  \midrule',
             f'  U100 RAW (base31) & +{m["u100_raw_net_annual"]["value"]*100:.1f}\\% & 0.31 & 46.3\\% & +{m["u100_raw_net_annual"]["value"]*100:.1f}\\% \\\\',
             f'  U50 RESID (base31) & {m["u50_resid_net_annual"]["value"]*100:+.1f}\\% & -0.04 & 61.3\\% & +4.9\\% \\\\',
             f'  U50 EW benchmark & -5.9\\% & -0.26 & — & — \\\\',
             r'  \bottomrule']
    
    with open(os.path.join(GEN_DIR, 'portfolio_results.tex'), 'w') as f:
        f.write('\n'.join(rows2))
    
    # Decision gates table
    rows3 = [r'  \toprule',
             r'  \textbf{Criterion} & \textbf{Result} & \textbf{Gate} \\',
             r'  \midrule',
             r'  Cross-sectional predictability & Passed & IC > 0, NW $t > 2$ \\',
             r'  Time-aware significance & Passed & Bootstrap CI excludes 0 \\',
             r'  Within-Q1 stock selection & Passed & Excess > 0 \\',
             r'  Positive liquid-universe return & Failed & U50 net < 0 \\',
             r'  Acceptable drawdown & Failed & Max DD > 25\% \\',
             r'  Scalable capacity & Failed & Q1 holds 48\% of capital \\',
             r'  \midrule',
             r'  \textbf{Final Decision} & \textbf{TERMINATED} & OHLCV-only branch closed \\',
             r'  \bottomrule']
    
    with open(os.path.join(GEN_DIR, 'decision_gates.tex'), 'w') as f:
        f.write('\n'.join(rows3))
    
    # Evidence map
    rows4 = [r'  \toprule',
             r'  \textbf{Metric Key} & \textbf{Experiment ID} & \textbf{Artifact} \\',
             r'  \midrule']
    for key in sorted(m.keys())[:15]:
        metric = m[key]
        rows4.append(f'  {esc(key)} & {esc(metric.get("experiment_id", "N/A"))} & {esc(metric.get("artifact", "N/A"))} \\\\')
    rows4.append(r'  \bottomrule')
    
    with open(os.path.join(GEN_DIR, 'evidence_map.tex'), 'w') as f:
        f.write('\n'.join(rows4))
    
    # Build manifest
    manifest = {
        'evidence_keys_used': len(m),
        'collapse_count': len(e.get('collapses', [])),
        'exhibit_count': len(e.get('exhibits', {}).get('primary', [])),
        'generated_files': [f for f in os.listdir(GEN_DIR) if f.endswith('.tex')]
    }
    with open(os.path.join(GEN_DIR, 'build_manifest.json'), 'w') as f:
        json.dump(manifest, f, indent=2)
    
    print(f"✅ Generated 4 table fragments + manifest")

def compile_latex():
    """Compile main.tex to PDF."""
    if not shutil.which('pdflatex'):
        print("⚠️  pdflatex not found. Skipping PDF compilation.")
        print(f"   Run 'pdflatex main.tex' manually in {REPORT_DIR}")
        return False
    
    for _ in range(2):
        result = subprocess.run(['pdflatex', '-interaction=nonstopmode', 'main.tex'],
                              cwd=REPORT_DIR, capture_output=True, text=True)
        if result.returncode != 0:
            # Extract errors
            err_lines = [l for l in result.stdout.split('\n') if l.startswith('!')]
            print(f"❌ LaTeX compilation failed ({len(err_lines)} errors)")
            for l in err_lines[:5]:
                print(f"   {l}")
            return False
    
    # Copy PDF to root
    src = os.path.join(REPORT_DIR, 'main.pdf')
    if os.path.exists(src):
        shutil.copy(src, OUTPUT)
        print(f"✅ PDF compiled: {OUTPUT}")
        return True
    return False

def main():
    validate()
    e = load_evidence()
    os.makedirs(GEN_DIR, exist_ok=True)
    generate_macros(e)
    generate_tables(e)
    compile_latex()

if __name__ == '__main__':
    main()
